# Generated by Django 3.1.4 on 2020-12-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax', models.CharField(max_length=20, unique=True)),
                ('hour', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoWorkingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=20, unique=True)),
                ('hour', models.SmallIntegerField()),
                ('whole_day', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(max_length=20, unique=True)),
                ('monthly', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=30, unique=True)),
                ('payment', models.SmallIntegerField()),
                ('co_working', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.coworkingspace')),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.conference')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.membership')),
            ],
        ),
    ]
