# Generated by Django 3.1.4 on 2020-12-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20201205_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax', models.CharField(max_length=20, unique=True)),
                ('hour', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.conference'),
        ),
    ]
